import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar, { Navigation } from '@/components/Navbar'
import Providers from '@/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const navigations: Navigation[] = [
  {
    label: "使用說明",
    route: "/instruction"
  },
  {
    label: "收費方式",
    route: "/payment"
  },
  {
    label: "站點資訊",
    route: "/site-info"
  },
  {
    label: "最新消息",
    route: "/news"
  },
  {
    label: "活動專區",
    route: "/event"
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar navigations={navigations} />
          {children}
        </Providers>
      </body>
    </html>
  )
}
